# name: 'Terraform'
 
# on:
#   workflow_dispatch:
#     inputs:
#       apply:
#         description: Whether to run terraform apply
#         default: "false"
#         required: true
#       branches:
#         default: main
#         required: true
#   pull_request:
  
name: Deploy Oracle Role
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
        branch:
          required: true
          default: main
 
jobs:
  terraform:
    name: 'Terraform'
#     env:
#       ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#       ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#       ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    runs-on: ubuntu-latest
#     environment: production
#     container:
#       image: hub.docker.com/r/rancher/ansible-runner
#       credentials:
#         username: vivek1509
#         password: Pass@321Vks
 
#     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
#     defaults:
#       run:
#         shell: bash
 
    
    # Checkout the repository to the GitHub Actions runner
    
 
#     - name: 'Terraform Format'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: 0.14.8
#         tf_actions_subcommand: 'fmt'
#         tf_actions_working_dir: "./terraform"
   
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
         username: vivek1509
         password: Pass@321Vks
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - uses: addnab/docker-run-action@v3
      with:
        username: vivek1509
        password: Pass@321Vks
        registry: hub.docker.com/r/rancher
        image: ansible-runner
        options: -v ${{ github.workspace }}:/work -e ABC=123
        run: |
           echo "Running Script"
           /work/run-script
         
         
         
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
 
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"
